# Generated by Django 3.2.23 on 2023-11-22 15:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddurovnhl/image/upload/v1698059495/samples/cloudinary-icon.png', max_length=255, verbose_name='post-image'),
        ),
    ]
