# Generated by Django 3.2.23 on 2023-12-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friends Only')], default=0),
        ),
    ]
