# Generated by Django 3.2.23 on 2023-11-28 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registerLoginLogout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='FriendRequests',
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profiles',
        ),
    ]
