# Generated by Django 3.2.23 on 2023-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLoginLogout', '0004_auto_20231130_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
